# Generated by Django 2.2.6 on 2019-10-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookings',
            new_name='booking',
        ),
    ]
